name : Warp
main : warp.Warp
version : 1.0-SNAPSHOT
author : mocha
api : [1.0.0]

permissions : 
 addwarp.cmd : 
  default : OP
 delwarp.cmd : 
  default : OP
 listwarp.cmd : 
  default : true
 warp.cmd : 
  default : OP